In [1]:
import pandas as pd

In [2]:
!pip install faker

Collecting faker
  Downloading faker-37.1.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tzdata in c:\users\santi\onedrive\escritorio\maestria\entornos\clases\lib\site-packages (from faker) (2025.2)
Downloading faker-37.1.0-py3-none-any.whl (1.9 MB)
   ---------------------------------------- 0.0/1.9 MB ? eta -:--:--
   -------------------------------------- - 1.8/1.9 MB 23.1 MB/s eta 0:00:01
   ---------------------------------------- 1.9/1.9 MB 12.5 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-37.1.0

In [3]:
from faker import Faker
fake = Faker()

In [4]:
lista = []

In [5]:
for x in range(0,51):
    lista.append({'nombre': fake.name()})

In [6]:
lista

[{'nombre': 'Brian Blair'},
 {'nombre': 'Kristen Palmer'},
 {'nombre': 'Kathryn West'},
 {'nombre': 'Melissa Rivera'},
 {'nombre': 'Teresa Fitzgerald'},
 {'nombre': 'Matthew Moody'},
 {'nombre': 'Darren Conrad PhD'},
 {'nombre': 'Kimberly Wilson'},
 {'nombre': 'Sarah Wallace'},
 {'nombre': 'Brittany Carson'},
 {'nombre': 'Kent Tapia'},
 {'nombre': 'Angela Gray'},
 {'nombre': 'Mr. Jason Larson'},
 {'nombre': 'Shawn Norris'},
 {'nombre': 'Sydney James'},
 {'nombre': 'Teresa Price'},
 {'nombre': 'Jennifer Thomas'},
 {'nombre': 'Carolyn Miller'},
 {'nombre': 'Alejandra Mayer'},
 {'nombre': 'Linda Krause'},
 {'nombre': 'Brian Beltran'},
 {'nombre': 'David Ruiz'},
 {'nombre': 'Rebecca Hansen'},
 {'nombre': 'Sarah Anderson'},
 {'nombre': 'Andrew Mays'},
 {'nombre': 'Christopher Good'},
 {'nombre': 'Thomas Cook'},
 {'nombre': 'Robert Taylor'},
 {'nombre': 'Jill Garza'},
 {'nombre': 'Audrey Patel'},
 {'nombre': 'Jeremy Mclean'},
 {'nombre': 'Karen Ward'},
 {'nombre': 'Johnathan Dougherty'},
 {'nombre': 'William Wood'},
 {'nombre': 'Brenda Hoover'},
 {'nombre': 'Mark Taylor'},
 {'nombre': 'Elizabeth Moore'},
 {'nombre': 'Christopher Jenkins'},
 {'nombre': 'Christopher Vargas'},
 {'nombre': 'Jason Jones'},
 {'nombre': 'Karen Stanley'},
 {'nombre': 'Melinda Hayden'},
 {'nombre': 'Kevin Vargas'},
 {'nombre': 'Richard Fisher'},
 {'nombre': 'John Juarez'},
 {'nombre': 'Candice Mcconnell'},
 {'nombre': 'Scott Williams'},
 {'nombre': 'Karina Hanna'},
 {'nombre': 'Kimberly Wilson'},
 {'nombre': 'Kevin Lowe'},
 {'nombre': 'Ashley Young'}]

In [7]:
data = pd.DataFrame(lista)

In [8]:
data

                 nombre
0           Brian Blair
1        Kristen Palmer
2          Kathryn West
3        Melissa Rivera
4     Teresa Fitzgerald
5         Matthew Moody
6     Darren Conrad PhD
7       Kimberly Wilson
8         Sarah Wallace
9       Brittany Carson
10           Kent Tapia
11          Angela Gray
12     Mr. Jason Larson
13         Shawn Norris
14         Sydney James
15         Teresa Price
16      Jennifer Thomas
17       Carolyn Miller
18      Alejandra Mayer
19         Linda Krause
20        Brian Beltran
21           David Ruiz
22       Rebecca Hansen
23       Sarah Anderson
24          Andrew Mays
25     Christopher Good
26          Thomas Cook
27        Robert Taylor
28           Jill Garza
29         Audrey Patel
30        Jeremy Mclean
31           Karen Ward
32  Johnathan Dougherty
33         William Wood
34        Brenda Hoover
35          Mark Taylor
36      Elizabeth Moore
37  Christopher Jenkins
38   Christopher Vargas
39          Jason Jones
40        Karen Stanley
41       Melinda Hayden
42         Kevin Vargas
43       Richard Fisher
44          John Juarez
45    Candice Mcconnell
46       Scott Williams
47         Karina Hanna
48      Kimberly Wilson
49           Kevin Lowe
50         Ashley Young

In [9]:
data.to_csv("misdata.csv", index=False)